Question 1

In [6]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
# Addition 
print(arr1+2)

# Multiplication
print(arr1*3)

# Divide
print(arr1/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Question 2 

In [7]:
arr2 = np.array([1,2,3,4,5,6])
reversed_arr = arr2[::-1]
print(reversed_arr)

def most_frequent(array):
    unique, counts = np.unique(array, return_counts=True)  
    most_frequent_value = unique[np.argmax(counts)] 
    indices = np.where(array == most_frequent_value)[0]  
    return most_frequent_value, indices

# (i) For x array
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_x, indices_x = most_frequent(x)
print("Most frequent value in x:", most_frequent_x)
print("Indices:", indices_x)

# (ii) For y array
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_y, indices_y = most_frequent(y)
print("Most frequent value in y:", most_frequent_y)
print("Indices:", indices_y)


[6 5 4 3 2 1]
Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


Question 3 

In [8]:
arr3 = np.array([
    [10, 20, 30], 
    [40, 50, 60], 
    [70, 80, 90]
])

element_a = arr3[0, 1]  
element_b = arr3[2, 0]  

print("Element at 1st row, 2nd column:", element_a)
print("Element at 3rd row, 1st column:", element_b)  


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Question 4

In [3]:
import numpy as np

mudrika = np.linspace(10, 100, 25)

print("Array:", mudrika)
print("Dimensions:", mudrika.ndim) 
print("Shape:", mudrika.shape)  
print("Total Elements:", mudrika.size)  
print("Data Type of Elements:", mudrika.dtype)  
print("Total Bytes Consumed:", mudrika.nbytes)  


transposed_array = mudrika.reshape(25, 1)
print("\nTransposed using reshape():\n", transposed_array)

print("\nTransposed using .T:\n", mudrika.T) 

print("\nIs reshaped array same as .T? :", np.array_equal(transposed_array, mudrika.T))


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type of Elements: float64
Total Bytes Consumed: 200

Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Is reshaped array same as .T? : False


Question 5 


In [4]:
ucs420_mudrika = np.array([
    [10, 20, 30, 40], 
    [50, 60, 70, 80], 
    [90, 15, 20, 35]
])

# Step 2: Compute statistics
mean_value = np.mean(ucs420_mudrika)     
median_value = np.median(ucs420_mudrika)  
reshaped_ucs420_mudrika = ucs420_mudrika.reshape(4, 3)
max_value = np.max(ucs420_mudrika)        
min_value = np.min(ucs420_mudrika)         
unique_values = np.unique(ucs420_mudrika)  

reshaped_ucs420_mudrika = ucs420_mudrika.reshape(4, 3)


resized_ucs420_mudrika = np.resize(ucs420_mudrika, (2, 3))

# Step 5: Print results
print("Original 3x4 Array (ucs420_):\n", ucs420_mudrika)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max Value:", max_value)
print("Min Value:", min_value)
print("Unique Elements:", unique_values)

print("\nReshaped (4x3) Array:\n", reshaped_ucs420_mudrika)
print("\nResized (2x3) Array:\n", resized_ucs420_mudrika)


Original 3x4 Array (ucs420_):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3) Array:
 [[10 20 30]
 [40 50 60]]
